= Webapp_Database

== Dokumentation

Dies ist eine Dokumentation für die Projektarbeit Webapp_Database. 

== Projektmitglieder (Contributors)

Melanie Gille, Jakob Friedrich, Tobias Lux

== Projektbeschreibung

Java Spring Boot

Warum:
Unter Verwendung von Java kommt das Spring Boot Framework zum Einsatz.

Dieses wird benutzt um einen Webserver (Apache Tomcat) out of the box mitgeliefert zu bekommen.
Außerdem wird das Backend benutzt um die JS / React Inhalte einfach mit der Datenbank kommunizieren zu lassen.

Um ein Spring Boot Projekt initial zu erstellen wird maven als automatisierungstool benutzt.
Dadurch werden alle dependencies hinzugefügt.

Datenbank deployen und Spring starten:

Zum deployen der Datenbank muss lediglich Docker(-Desktop) installiert sein.
Wenn das geschehen ist, können die Container gestartet werden. Dafür ist bereits eine Konfigurationsdatei bereitgestellt, das docker-compose file.
Um mit hilfe dessen die Container Umgebung zu starten, muss man folgende Schritte unternehmen:
Commandline(Ausgang vom Projektordner)

cd docker

docker-compose up -d

Außerdem muss das Backend gestartet werden. Dies kann je nach IDE in der Main Class gemacht werden. In dem Fall
unseres Projektes: WebAppDatabase.java

== Front-End

Logo Quelle: https://logo-maker.freelogodesign.org/de?companyName=Jameto&_gl=1*zl079a*_ga*OTQxMjk2MTA3LjE2NzQ1MDM4MjA.*_ga_0PR6284HMM*MTY3NDUwMzgxOS4xLjAuMTY3NDUwMzgxOS42MC4wLjA.&category=23

Profil Banner Quelle:
https://cdn3.f-cdn.com/contestentries/1683544/29258875/5de652e07bf20_thumb900.jpg 

Für das Front-End nutzten wir React.js, welches eine Javascript Bibliothek ist. Damit konnten wir unsere Webseite nach belieben gestalten und ein Script einfügen mit welchem die Webseite eine Kommunikation mit der Datenbank aufbaut.

Front-End starten:
----
cd Webapp_FrontEnd
npm start
----

Datenbank test 
SpringBoot Debug
Einträge API: http://localhost:8080/api/v1/applicant/register

Im Webapp_FrontEnd:
----
mvn clean install
----
kopieren von inhalt des Webapp_FrontEnd/target/build Ordners in:
Webapp_Full/src/main/resources/static/

application.properties: spring.datasource.url ändern zu postgres_db
Java Applikation erstellen:
Maven Webapp_BackEnd:
----
mvn clean compile package install
----
=> .jar wird erstellt
----
docker build -f(ile) .\dockerfile -t(arget) webapp/webapp:latest .
----
=> Docker image wird erstellt
----
docker save webapp/webapp:latest -o(utput) webapp.tar
----
=> tar für Backend erstellen

=> ein Image für einen Container (zweiter Container enthält nginx.conf)
----
scp .\WebApp_Full\webapp.tar .\docker\nginx\conf\webapp.conf .\docker\docker-compose.yml user@10.0.211.194:/home/user/
----
=> ssh copy secure: zwei .tar, nginx.conf und docker-compose wird auf VM kopiert in den User Home folder
----
ssh user@10.0.211.194

sudo docker load --input ./webapp.tar

docker-compose up -d
----
