services:
  nginx:
    image: nginx:latest
    container_name: webapp-nginx
    restart: always
    environment:
      - TZ=Europe/Berlin
    volumes:
      - ./nginx/conf/webapp.conf:/etc/nginx/conf.d/default.conf
      #- ./nginx/conf/pgadmin4.conf:/nginx/conf.d/pgadmin4.conf
    ports:
      - 80:80
    networks:
      - nginx-net

  postgres:
    image: postgres:latest
    container_name: postgres_db
    restart: always
    volumes:
      - postgresql_data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    expose:
      - 5432
    environment:
      - TZ=Europe/Berlin
      - POSTGRES_USER=dumbo
      - POSTGRES_PASSWORD=dumbo1234!
      - POSTGRES_DB=user_management
    networks:
      - db-net
  webapp:
    image: webapp/webapp:latest
    container_name: webapp
    restart: always
    expose:
      - 8080
    networks:
      - db-net
      - nginx-net

volumes:
  postgresql_data:
    driver: local

networks:
  nginx-net: #Only Connection between React Application and Nginx
  db-net: #Only Connection between Spring Application and Postgres
