services:
  nginx:
    image: nginx:latest
    container_name: webapp-nginx
    restart: always
    environment:
      - TZ=Europe/Berlin
    volumes:
      - ./nginx/conf/webapp.conf:/etc/nginx/conf.d/webapp.conf
      #- ./nginx/conf/pgadmin4.conf:/nginx/conf.d/pgadmin4.conf
    ports:
      - 80:443
    networks:
      - nginx-net

  pgadmin4:
    image: dpage/pgadmin4:latest
    container_name: pgadmin4
    restart: always
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.admin
      - PGADMIN_DEFAULT_PASSWORD=admin
    ports:
      - "5050:80"
    networks:
      - nginx-net
      - db-net
    volumes:
      - ./pgadmin4/servers.json:/pgadmin4/servers.json

  postgres:
    image: postgres:latest
    container_name: postgres_db
    restart: always
    volumes:
      - postgresql_data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      - TZ=Europe/Berlin
      - POSTGRES_USER=dumbo
      - POSTGRES_PASSWORD=dumbo1234!
      - POSTGRES_DB=user_management
    networks:
      - db-net

volumes:
  postgresql_data:
    driver: local

networks:
  nginx-net: #Only Connection between Application and Nginx
  db-net: #Only Connection between Application and Postgres
